package it.polimi.ingsw.network;

public enum Error {
    UNKNOWN_ERROR,
    USERNAME_NOT_FOUND,
    INVALID_GAME_MODE,
    GAME_ALREADY_STARTED,
    GAME_ALREADY_EXISTING,
    GAME_NOT_FOUND,
    INVALID_USERNAME,
    INVALID_NUM_PLAYER,
    INVALID_DIFFICULTY,

    INVALID_ACTION,
    WRONG_ACTION,
    WRONG_PLAYER,

    NOT_ENOUGH_MONEY,
    INVALID_REMOVAL_HALL_STUDENT,
    INVALID_REMOVAL_ENTRANCE_STUDENT,
    INVALID_REMOVAL_CLOUD_STUDENT,
    INVALID_REMOVAL_ISLAND_STUDENT,
    INVALID_MN_SHIFT;
}
