package it.polimi.ingsw.network;

public enum Phase {
    LOGIN,
    SETTINGS,
    LOBBY,
    START,
    WAITING,
    PLAYING, JOINING, CHOSING_SCHOOLBOARD, CHOSING_ASSISTANT_CARD, CHOOSING_PAWS_TO_MOVE, CHOOSING_MN_MOVE, CHOOSING_CLOUDTILE, LOBBY_WAITING, CHOOSING_PARAMETER,
}
