package it.polimi.ingsw.network;

public enum Phase {
    LOGIN,
    SETTINGS,
    PLANNING,
    CHOOSING_FIRST_MOVE,
    CHOOSING_SECOND_MOVE,
    CHOOSING_THIRD_MOVE,
    CHOOSING_MN_SHIFT,
    CHOOSING_CT,
    CHOOSING_CHARACTER_CARD,
    CHOOSING_PARAMETERS,
    WAITING, END_GAME,

}
